### ISSUE TITLE
add preprocessor step to the train/test_pipeline

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pytorch-ie-hydra-template-1#5]
This should allow to do sth like sentence splitting before feeding the documents to TaskModule.prepare, e.g.:
```python
...
# Init pytorch-ie dataset
log.info(f"Instantiating dataset <{config.dataset._target_}>")
dataset: Dict[str, Dataset] = hydra.utils.instantiate(config.dataset)

# new content
# preprocess pytorch-ie dataset
if config.get("preprocessor", None):
  log.info(f"Instantiating preprocessors")
  preprocessor = hydra.utils.instantiate(config.preprocessor)
  for p_name, p_with_kwargs in preprocessor.items():
      log.info(f"apply preprocessor {p_name} ...")
      # p_with_kwargs contains the preprocessor and, optionally, the kwargs 
      p = p_with_kwargs[0]
      p_kwargs = p_with_kwargs[1] if len(p_with_kwargs) > 1 else {}
      dataset = {k: v.map(p, **p_kwargs) for k, v in dataset.items()}

...
```

and with config entries like:
```yaml
split_sentences:
  - _target_: SentenceAnnotator
    model: ...

add_negative_relations:
  - _target_: NegativeRelationAdder
  # kwargs passed to Dataset.map:
  - batched: True
    batch_size: 100
  ...
```

related issue in pytorch-ie: https://github.com/ChristophAlt/pytorch-ie/issues/169
